"""Google Colab GPU integration and bundle packager for DualSPHysics (Phase 3)."""

from __future__ import annotations

import json
import logging
import tarfile
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

    from pravahx.engines.base import PreparedCase

logger = logging.getLogger(__name__)


def export_colab_case_package(case: PreparedCase, output_tar: Path) -> Path:
    """Package prepared DualSPHysics case into a standalone tar.gz for Google Colab.

    Args:
        case: PreparedCase generated by DualSPHysicsBuilder.
        output_tar: Target tar.gz path.

    Returns:
        Path to the generated archive.
    """
    output_tar.parent.mkdir(parents=True, exist_ok=True)
    xml_name = case.metadata.get("case_xml", "Case_Def.xml")
    case_base = xml_name.replace("_Def.xml", "").replace(".xml", "")

    # Runner shell script for Colab
    run_script = f"""#!/bin/bash
set -e
echo "=================================================="
echo " PravahX DualSPHysics GPU Runner (Google Colab)"
echo "=================================================="

# Check NVIDIA GPU
nvidia-smi

# 1. Run GenCase
echo "--> Step 1/3: Running GenCase..."
gencase {xml_name} {case_base} -save:all

# 2. Run DualSPHysics GPU
echo "--> Step 2/3: Running DualSPHysics GPU solver..."
dualsphysics_gpu {case_base} output -gpu -dirdataout data -svres

# 3. Extract particles and gauges
echo "--> Step 3/3: Running PartVTK and MeasureTool..."
partvtk -dirin output/data -fileout output/PartFluid -vars:all -savevtk output/PartFluid.vtk || true
measuretool -dirin output/data -fileout output/MeasureTool_Gauges -savecsv || true

# 4. Generate SHA-256 Manifest
echo "--> Generating cryptographic SHA-256 manifest..."
python3 -c "
import hashlib, json, os
manifest = {{'files': {{}}}}
for root, _, files in os.walk('output'):
    for f in files:
        if f == 'manifest.json':
            continue
        p = os.path.join(root, f)
        rel = os.path.relpath(p, 'output')
        with open(p, 'rb') as fp:
            manifest['files'][rel] = hashlib.sha256(fp.read()).hexdigest()
with open('output/manifest.json', 'w') as mf:
    json.dump(manifest, mf, indent=2)
print(f'Manifest generated with {{len(manifest[\"files\"])}} files.')
"

# 5. Compress results
tar -czf dualsphysics_results.tar.gz -C output .
echo "=================================================="
echo " Execution Complete: dualsphysics_results.tar.gz"
echo "=================================================="
"""

    script_path = case.case_dir / "run_colab.sh"
    script_path.write_text(run_script, encoding="utf-8")

    with tarfile.open(output_tar, "w:gz") as tar:
        tar.add(case.case_dir / xml_name, arcname=xml_name)
        tar.add(script_path, arcname="run_colab.sh")

    logger.info("Exported Google Colab case package: %s", output_tar)
    return output_tar


def create_colab_notebook_content() -> str:
    """Generate the complete JSON string for the Google Colab runner notebook."""
    dl_url_52 = (
        "https://github.com/DualSPHysics/DualSPHysics/releases/download/"
        "v5.2.1/DualSPHysics_v5.2.1_Linux_x64.zip"
    )
    dl_url_50 = (
        "https://github.com/DualSPHysics/DualSPHysics/releases/download/"
        "v5.0/DualSPHysics_v5.0_Linux_x64.zip"
    )

    notebook_dict: dict[str, Any] = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# PravahX — DualSPHysics Google Colab GPU Runner\n",
                    "\n",
                    "This notebook runs 3D SPH dam break and surge simulations on a "
                    "**Google Colab GPU (NVIDIA Tesla T4 / V100 / A100)**.\n",
                    "\n",
                    "### Workflow:\n",
                    "1. Verify GPU acceleration.\n",
                    "2. Download and set up DualSPHysics Linux x64 CUDA binaries.\n",
                    "3. Upload your prepared `dualsphysics_case.tar.gz` from PravahX.\n",
                    "4. Execute the simulation and generate cryptographic SHA-256 manifest.\n",
                    "5. Download `dualsphysics_results.tar.gz` for import into PravahX.\n",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": ["# Step 1: Check GPU\n", "!nvidia-smi"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Step 2: Download & Extract DualSPHysics Linux Binaries\n",
                    "import os\n",
                    "\n",
                    "!mkdir -p /content/dualsphysics && cd /content/dualsphysics\n",
                    f"!wget -q -O /content/dualsphysics_bin.zip {dl_url_52} || \\\n",
                    f" wget -q -O /content/dualsphysics_bin.zip {dl_url_50}\n",
                    "!unzip -q /content/dualsphysics_bin.zip -d /content/dualsphysics || true\n",
                    "os.environ['PATH'] += ':/content/dualsphysics/bin/linux'",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Step 3: Upload Case Package\n",
                    "import tarfile\n",
                    "from google.colab import files\n",
                    "\n",
                    "print('Upload your dualsphysics_case.tar.gz prepared by PravahX:')\n",
                    "uploaded = files.upload()\n",
                    "for fn in uploaded:\n",
                    "    if fn.endswith('.tar.gz') or fn.endswith('.tgz'):\n",
                    "        with tarfile.open(fn, 'r:gz') as tar:\n",
                    "            tar.extractall(path='/content/run')\n",
                    "        print(f'Extracted {fn} to /content/run')",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Step 4: Execute Simulation on GPU\n",
                    "%%bash\n",
                    "cd /content/run\n",
                    "chmod +x run_colab.sh\n",
                    "./run_colab.sh",
                ],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Step 5: Download Verified Results Package\n",
                    "from google.colab import files\n",
                    "import os\n",
                    "\n",
                    "results_path = '/content/run/dualsphysics_results.tar.gz'\n",
                    "if os.path.exists(results_path):\n",
                    "    print('Downloading results package for PravahX import...')\n",
                    "    files.download(results_path)\n",
                    "else:\n",
                    "    print('Error: dualsphysics_results.tar.gz not found.')",
                ],
            },
        ],
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": []},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }
    return json.dumps(notebook_dict, indent=2)
