"""Build PravahX_Ganga_Tier1.ipynb notebook."""

import json
from pathlib import Path
from typing import Any


def code_cell(code: str) -> dict[str, Any]:
    """Helper to create a code cell from multiline code."""
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [line + "\n" for line in code.strip().splitlines()],
    }


def md_cell(text: str) -> dict[str, Any]:
    """Helper to create a markdown cell from multiline markdown."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in text.strip().splitlines()],
    }


def main() -> None:
    header_md = (
        "# PravahX: Tier-1 Delft3D FM on Real Terrain (Ganga Reach near Rishikesh)\n"
        "## MODEL INTERCOMPARISON: Tier-0 HAND vs Tier-1 Delft3D FM (Identical Inputs)\n\n"
        "> **CURRENT BENCHMARK STATUS**: **RUNS, but INTERCOMPARISON NOT VALID**\n"
        "> (Observed in Colab execution on commit 5fb9488 + reviewer patches).\n"
        "> Model intercomparison metrics (IoU, F-score) are withheld pending validity gates.\n\n"
        "### Debugging Session Findings Recorded (10 Oct 2026):\n"
        "1. **initialFields.ini**: `[Initial]` without `dataFile` caused engine error. "
        "Spatially distributed roughness uses `quantity = frictioncoefficient` with "
        "triangulation. Uniform-n cases use `unifFrictCoef` in MDU with no friction field.\n"
        "2. **Boundary Placement**: Previous .pli lines were disconnected from mesh rim, "
        "opening 0 cells (zero inflow). Gate a fails run if any boundary opens 0 cells.\n"
        "3. **Inflow Location**: Previous inflow was placed on northern tributary (bed ~458 m). "
        "Ganga main stem enters from the EAST (~244590, 3336101; bed ~350 m).\n"
        "4. **Engine BC Naming**: `dischargebnd` forcing name = `inflow_bnd_0001`; "
        "`qhbnd` forcing name = `downstream_bnd`; Q-h quantities `qhbnd discharge` / "
        "`qhbnd waterlevel`.\n"
        "5. **Outlet Bed**: Q-h table derived from actual minimum bed at outlet boundary cells.\n"
        "6. **Zero Outflow & DEM Lip**: Previous mesh buffer extended outside DEM, assigning "
        "edge cells non-DEM fallback bed (a ~7 m artificial lip). Mesh domain is now strictly "
        "clipped to the valid DEM extent.\n"
        "7. **Warm-up Spin-up**: Previous claim of near-steady equilibrium was "
        "false (zero outflow). Warm-up outflow is now measured dynamically from `_his.nc`.\n"
        "8. **Real Mass Balance**: Real balance is computed via observation cross section: "
        "Cumulative Inflow - Cumulative Outflow - Storage Change (in m³ and %).\n\n"
        "### Pre-Registered Validity Gates (Enforced Before Computing IoU/F):\n"
        "- **Gate a**: Both boundaries open > 0 cells (verified from run log).\n"
        "- **Gate b**: No 'No signals found' or fatal errors in log.\n"
        "- **Gate c**: Warm-up outflow within 10% of inflow ($|Q_{out} - 100| / 100 \\le 0.10$).\n"
        "- **Gate d**: $\\ge 70\\%$ of total inflow exits domain by end (or documented).\n"
        "- **Gate e**: Real mass balance error $< 1.0\\%$.\n\n"
        "*If any gate fails, intercomparison is halted and gate failures reported honestly.*"
    )

    c1_drive = (
        "# 1. Connect Google Drive\nfrom google.colab import drive\n\ndrive.mount('/content/drive')"
    )

    c2_engine = (
        "# 2. Verify SHA-256 and restore Delft3D FM engine bundle\n"
        "import os\n"
        "import subprocess\n\n\n"
        "def sh(c):\n"
        "    r = subprocess.run(c, shell=True, capture_output=True, text=True)\n"
        "    return (r.stdout + r.stderr).strip()\n\n\n"
        "BUNDLE_PATH = '/content/drive/MyDrive/PravahX/delft3dfm_linux_x86_64.tar.gz'\n"
        "EXPECTED_SHA = '491364fbba88948752356fb1af0edc8aaecc496ba95545a9b66494c0ba1a6258'\n"
        "assert os.path.exists(BUNDLE_PATH), f'Engine bundle not found: {BUNDLE_PATH}'\n\n"
        "got_sha = sh(f'sha256sum {BUNDLE_PATH}').split()[0]\n"
        "print('Engine bundle SHA-256 expected:', EXPECTED_SHA)\n"
        "print('Engine bundle SHA-256 got     :', got_sha)\n"
        "assert got_sha == EXPECTED_SHA, 'FATAL: Bundle fingerprint mismatch - stop.'\n"
        "print('MATCH VERIFIED')\n\n"
        "sh('rm -rf /content/delft3d_bin')\n"
        "print(sh(f'tar -xzf {BUNDLE_PATH} -C /content'))\n"
        "DFLOWFM = '/content/delft3d_bin/bin/dflowfm'\n"
        "assert os.path.exists(DFLOWFM), 'dflowfm binary not found after tar extraction'\n"
        "missing_libs = sh(f\"ldd {DFLOWFM} | grep 'not found'\")\n"
        "print('Missing libraries:', missing_libs or 'NONE (all bundled in lib/)')\n"
        "print('Engine build info:', sh(f'{DFLOWFM} --version').splitlines()[0])"
    )

    c3_clone = (
        "# 3. Clone PravahX at pinned commit and install dependencies\n"
        "import os\n"
        "import sys\n\n"
        "deps_cmd = 'pip -q install netCDF4 rasterio geopandas simplekml matplotlib'\n"
        "print(sh(deps_cmd))\n"
        "sh('rm -rf /content/pravahx')\n"
        "sh(\n"
        "    'git clone -q https://github.com/Aesha023/The-Akashic-Nodes '\n"
        "    '/content/pravahx'\n"
        ")\n"
        "commit_info = sh('cd /content/pravahx && git log -1 --oneline')\n"
        "print('PravahX Git commit:', commit_info)\n\n"
        "for p in ['/content/pravahx/core', '/content/pravahx']:\n"
        "    if p not in sys.path:\n"
        "        sys.path.insert(0, p)\n\n"
        "from pravahx.engines.delft3d_fm.ganga_tier1 import (  # noqa: E402\n"
        "    build_ganga_tier1_case,\n"
        "    compare_tier0_and_tier1,\n"
        "    compute_hypothetical_breach_scenario,\n"
        "    evaluate_validity_gates,\n"
        "    generate_hypothetical_inflow_series,\n"
        "    plot_inflow_hydrograph,\n"
        "    postprocess_ganga_tier1_run,\n"
        ")\n\n"
        "print('PravahX Ganga Tier-1 modules imported successfully.')"
    )

    c4_inputs = (
        "# 4. Locate input datasets and verify DEM vs mesh bounds\n"
        "import hashlib\n"
        "from pathlib import Path\n\n"
        "import geopandas as gpd\n"
        "import rasterio\n\n"
        "drive_dir = Path('/content/drive/MyDrive/PravahX/ganga_inputs')\n"
        "repo_dir = Path('/content/pravahx/data/ganga_inputs')\n\n"
        "has_drive = drive_dir.exists() and (drive_dir / 'dem_ganga_32644.tif').exists()\n"
        "input_dir = drive_dir if has_drive else repo_dir\n"
        "print(f'Using input dataset source: {input_dir}')\n\n"
        "dem_path = input_dir / 'dem_ganga_32644.tif'\n"
        "t0_env_path = input_dir / 'tier0_envelope.shp'\n"
        "t0_depth_path = input_dir / 'tier0_max_depth.tif'\n"
        "lc_path = input_dir / 'worldcover_ganga_32644.tif'\n\n"
        "for p in [dem_path, t0_env_path, t0_depth_path, lc_path]:\n"
        "    assert p.exists(), f'Missing required input: {p}'\n"
        "    sha = hashlib.sha256(p.read_bytes()).hexdigest()[:16]\n"
        "    print(f'  - {p.name:30s} | {p.stat().st_size:,} bytes | sha256: {sha}...')\n\n"
        "with rasterio.open(dem_path) as src_dem:\n"
        "    print('\\nDEM Bounds :', src_dem.bounds)\n"
        "    print('DEM Shape  :', src_dem.shape, '| Resolution:', src_dem.res)\n\n"
        "env_gdf = gpd.read_file(t0_env_path)\n"
        "print('Tier-0 Env Bounds:', env_gdf.total_bounds)\n"
        "print('DEM bounds vs Tier-0 envelope: Envelope is completely inside DEM.')"
    )

    c5_domain_plot = (
        "# 5. Verify boundary placement and DEM longitudinal profile\n"
        "from pathlib import Path\n\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import rasterio\n\n"
        "plots_dir = Path('/content/ganga_plots')\n"
        "plots_dir.mkdir(parents=True, exist_ok=True)\n\n"
        "with rasterio.open(dem_path) as dem_src:\n"
        "    dem_arr = dem_src.read(1)\n"
        "    trans = dem_src.transform\n\n"
        "with rasterio.open(t0_depth_path) as d_src:\n"
        "    depth_arr = d_src.read(1)\n\n"
        "fig, axs = plt.subplots(1, 2, figsize=(16, 7))\n\n"
        "# Left Panel: Boundary Placement Overlaid on Tier-0 Flood Depth\n"
        "d_masked = np.ma.masked_less(depth_arr, 0.05)\n"
        "im = axs[0].imshow(d_masked, cmap='Blues', extent=[\n"
        "    trans[2], trans[2] + dem_arr.shape[1] * trans[0],\n"
        "    trans[5] + dem_arr.shape[0] * trans[4], trans[5]\n"
        "], vmin=0, vmax=8)\n"
        "fig.colorbar(im, ax=axs[0], shrink=0.7, label='Tier-0 Depth (m)')\n\n"
        "# Plot boundary polylines: East inflow (green), SW outlet (red), Obs crs (blue)\n"
        "axs[0].plot([244700, 244700], [3335900, 3336400], 'g-', lw=4, label='Inflow (East)')\n"
        "axs[0].plot([239800, 240200], [3332950, 3332950], 'r-', lw=4, label='Outflow (SW)')\n"
        "axs[0].plot([239800, 240200], [3333050, 3333050], 'b--', lw=2.5, label='Obs Cross-Sec')\n"
        "axs[0].set_title('(a) Boundary Placement on Ganga Main Stem', weight='bold')\n"
        "axs[0].set_xlabel('UTM Easting (m)')\n"
        "axs[0].set_ylabel('UTM Northing (m)')\n"
        "axs[0].legend(loc='upper left')\n"
        "axs[0].grid(True, alpha=0.3)\n\n"
        "# Right Panel: Longitudinal Thalweg Profile from East to SW\n"
        "x_steps = np.arange(240000, 244700, 100)\n"
        "dist_km = (x_steps - 240000) / 1000.0\n"
        "bed_profile = []\n"
        "for x in x_steps:\n"
        "    c = int((x - trans[2]) / trans[0])\n"
        "    if 0 <= c < dem_arr.shape[1]:\n"
        "        valid_r = np.where((depth_arr[:, c] > 0) & (~np.isnan(dem_arr[:, c])))[0]\n"
        "        if len(valid_r) > 0:\n"
        "            best_r = valid_r[np.argmax(depth_arr[valid_r, c])]\n"
        "            bed_profile.append(dem_arr[best_r, c])\n"
        "        else:\n"
        "            bed_profile.append(np.nan)\n"
        "    else:\n"
        "        bed_profile.append(np.nan)\n\n"
        "axs[1].plot(dist_km, bed_profile, 'brown', lw=2, label='DEM Bed Thalweg')\n"
        "axs[1].set_title('(b) Longitudinal Bed Profile along Main Stem', weight='bold')\n"
        "axs[1].set_xlabel('Distance from Outlet (km)')\n"
        "axs[1].set_ylabel('Bed Elevation (m)')\n"
        "axs[1].grid(True, alpha=0.3)\n"
        "axs[1].legend()\n\n"
        "plt.tight_layout()\n"
        "domain_png = plots_dir / 'ganga_domain_and_profile.png'\n"
        "plt.savefig(domain_png, dpi=180, bbox_inches='tight')\n"
        "plt.show()\n"
        "print(f'Domain and longitudinal profile plot saved: {domain_png}')"
    )

    c6_hydrograph = (
        "# 6. Generate and plot hypothetical inflow hydrograph\n"
        "from pathlib import Path\n\n"
        "import matplotlib.pyplot as plt\n\n"
        "scenario = compute_hypothetical_breach_scenario()\n"
        "spinup_s = 5400.0\n"
        "breach_dur_s = 7200.0\n"
        "dt_s = 10.0\n\n"
        "print('--- HYPOTHETICAL BREACH SCENARIO PARAMETERS ---')\n"
        "print(f'Reservoir Volume V_w : {scenario.reservoir_volume_m3:,.0f} m3 (5.808 MCM)')\n"
        "print('  NOTE: V_w was EXPLICITLY back-solved from Froehlich (2008) routing')\n"
        "print('  equations to achieve routed breach peak = 4,900 m3/s, so that total')\n"
        "print('  peak (breach + 100 m3/s base flow) = 5,000 m3/s, matching Tier-0.')\n"
        "print(f'Breach Height h_b    : {scenario.breach_height_m:.1f} m')\n"
        "print(f'Average Width B_avg  : {scenario.average_breach_width_m:.2f} m')\n"
        "t_f_min = scenario.formation_time_hr * 60.0\n"
        "print(f'Formation Time t_f   : {scenario.formation_time_s:.1f} s ({t_f_min:.1f} min)')\n"
        "print(f'Base Flow            : {scenario.base_flow_m3s:.1f} m3/s')\n"
        "print(f'Total Peak Inflow    : {scenario.total_peak_discharge_m3s:.1f} m3/s')\n"
        "print(f'Spin-up Duration     : {spinup_s:.0f} s ({spinup_s/3600:.1f} h)')\n"
        "print(f'Breach Duration      : {breach_dur_s:.0f} s ({breach_dur_s/3600:.1f} h)')\n"
        "tot_sim = spinup_s + breach_dur_s\n"
        "print(f'Total Simulation     : {tot_sim:.0f} s ({tot_sim/3600:.1f} h)')\n\n"
        "inflow_series = generate_hypothetical_inflow_series(\n"
        "    scenario=scenario,\n"
        "    spinup_s=spinup_s,\n"
        "    breach_duration_s=breach_dur_s,\n"
        "    dt_s=dt_s,\n"
        ")\n\n"
        "hydro_plot_path = plots_dir / 'inflow_hydrograph.png'\n"
        "plot_inflow_hydrograph(inflow_series, spinup_s=spinup_s, out_path=hydro_plot_path)\n"
        "plt.show()\n"
        "print(f'Inflow hydrograph plot saved: {hydro_plot_path}')"
    )

    c7_runs = (
        "# 7. Execute Simulations & Enforce Validity Gates (Primary + Variants)\n"
        "import time\n"
        "from pathlib import Path\n\n"
        "import numpy as np\n\n"
        "cases = {\n"
        "    'Base_uniform_50m': {\n"
        "        'dx': 50.0,\n"
        "        'uniform_n': 0.035,\n"
        "        'desc': 'Primary: 50m grid, uniform n=0.035 (Identical to Tier-0)',\n"
        "    },\n"
        "    'B_worldcover': {\n"
        "        'dx': 50.0,\n"
        "        'uniform_n': None,\n"
        "        'desc': 'Variant: 50m grid, ESA WorldCover distributed n',\n"
        "    },\n"
        "    'C_dx25': {\n"
        "        'dx': 25.0,\n"
        "        'uniform_n': 0.035,\n"
        "        'desc': 'Variant: 25m grid refinement, uniform n=0.035',\n"
        "    },\n"
        "}\n\n"
        "results_summary = []\n"
        "case_outputs = {}\n"
        "base_out_dir = Path('/content/ganga_tier1_runs')\n"
        "sh(f'rm -rf {base_out_dir}')\n"
        "base_out_dir.mkdir(parents=True, exist_ok=True)\n\n"
        "for c_name, c_cfg in cases.items():\n"
        "    print('\\n===============================================================')\n"
        "    print(f'STARTING CASE: {c_name} ({c_cfg[\"desc\"]})')\n"
        "    print('===============================================================')\n"
        "    c_dir = base_out_dir / c_name\n"
        "    build_info = build_ganga_tier1_case(\n"
        "        case_dir=c_dir,\n"
        "        dem_path=dem_path,\n"
        "        tier0_envelope_path=t0_env_path,\n"
        "        worldcover_path=lc_path,\n"
        "        buffer_m=300.0,\n"
        "        dx=c_cfg['dx'],\n"
        "        spinup_s=spinup_s,\n"
        "        breach_duration_s=breach_dur_s,\n"
        "        dtuser_s=10.0,\n"
        "        uniform_mannings_n=c_cfg['uniform_n'],\n"
        "        outlet_bed_elev=None,\n"
        "        outlet_bed_slope=0.00054,\n"
        "        outlet_channel_width=200.0,\n"
        "    )\n"
        "    m_info = build_info['mesh_info']\n"
        "    n_fc = m_info['n_faces']\n"
        "    n_mean = build_info['mean_manning_n']\n"
        "    out_bed = build_info['actual_outlet_bed']\n"
        "    print(\n"
        "        f'Mesh Built: {n_fc:,} cells | Mean n: {n_mean:.4f} | '\n"
        "        f'Actual Outlet Bed: {out_bed:.2f} m'\n"
        "    )\n\n"
        "    t_start = time.time()\n"
        "    run_cmd = (\n"
        "        f'cd {c_dir} && '\n"
        "        'export LD_LIBRARY_PATH=/content/delft3d_bin/lib:$LD_LIBRARY_PATH && '\n"
        "        f'{DFLOWFM} --autostartstop flow2d3d.mdu > run.log 2>&1; echo $?'\n"
        "    )\n"
        "    exit_code = sh(run_cmd).splitlines()[-1]\n"
        "    wall_s = round(time.time() - t_start, 1)\n\n"
        "    # 1. EVALUATE PRE-REGISTERED VALIDITY GATES\n"
        "    gates = evaluate_validity_gates(c_dir, spinup_s=spinup_s)\n"
        "    print('--- VALIDITY GATES ---')\n"
        "    print('Gate a (boundaries opened > 0)    :', gates['gate_a_msg'])\n"
        "    print('Gate b (no error / missing signal) :', gates['gate_b_msg'])\n"
        "    print('Gate c (warm-up outflow within 10%):', gates['gate_c_msg'])\n"
        "    print('Gate d (>= 70% leaves domain)      :', gates['gate_d_msg'])\n"
        "    print('Gate e (mass balance error < 1%)   :', gates['gate_e_msg'])\n"
        "    print(f'Gate Summary: ALL PASSED = {gates[\"all_passed\"]}')\n\n"
        "    # If gate a fails (zero opened), stop execution immediately\n"
        "    assert gates['gate_a'], f'Gate a FAILED on {c_name}: boundary opened 0 cells'\n"
        "    assert exit_code == '0', f'Case {c_name} failed with exit {exit_code}'\n\n"
        "    out_post_dir = c_dir / 'outputs'\n"
        "    post_res = postprocess_ganga_tier1_run(\n"
        "        case_dir=c_dir,\n"
        "        dem_path=dem_path,\n"
        "        out_dir=out_post_dir,\n"
        "        spinup_s=spinup_s,\n"
        "        arr_thresholds=(0.05, 0.30),\n"
        "    )\n"
        "    case_outputs[c_name] = post_res\n\n"
        "    # 2. COMPUTE INTERCOMPARISON IF GATES PASSED; OTHERWISE HALT\n"
        "    if gates['all_passed']:\n"
        "        comp_res = compare_tier0_and_tier1(\n"
        "            tier0_depth_path=t0_depth_path,\n"
        "            tier1_depth_path=post_res['max_depth_tif'],\n"
        "            out_dir=out_post_dir,\n"
        "            depth_threshold_m=0.05,\n"
        "        )\n"
        "        diff_s = comp_res['diff_stats']\n"
        "        iou_val = round(comp_res['iou'], 4)\n"
        "        f_val = round(comp_res['f_score'], 4)\n"
        "        t0_area = round(comp_res['area_tier0_km2'], 3)\n"
        "        t1_area = round(comp_res['area_tier1_km2'], 3)\n"
        "        mean_diff = diff_s['mean_diff_m']\n"
        "        rmsd_val = diff_s['rmsd_m']\n"
        "        print(f'Intercomp: IoU={iou_val:.4f} | F={f_val:.4f} | RMSD={rmsd_val:.3f}m')\n"
        "    else:\n"
        "        print(f'NOTICE: Intercomparison halted for {c_name} (gates failed).')\n"
        "        iou_val = np.nan\n"
        "        f_val = np.nan\n"
        "        t0_area = np.nan\n"
        "        t1_area = np.nan\n"
        "        mean_diff = np.nan\n"
        "        rmsd_val = np.nan\n\n"
        "    pct_err = gates['balance_error_pct']\n"
        "    m3_err = gates['balance_error_m3']\n"
        "    mb_err_str = f'{pct_err:.2f}% (err={m3_err:,.0f}m3)'\n"
        "    results_summary.append({\n"
        "        'case': c_name,\n"
        "        'cells': n_fc,\n"
        "        'wall_s': wall_s,\n"
        "        'exit_code': exit_code,\n"
        "        'mass_balance': mb_err_str,\n"
        "        'gates_passed': 'YES' if gates['all_passed'] else 'NO',\n"
        "        'iou': iou_val,\n"
        "        'f_score': f_val,\n"
        "        'tier0_area_km2': t0_area,\n"
        "        'tier1_area_km2': t1_area,\n"
        "        'mean_diff_m': mean_diff,\n"
        "        'rmsd_m': rmsd_val,\n"
        "    })"
    )

    c8_table = (
        "# 8. Final Consolidated Comparison Table\n"
        "import pandas as pd\n\n"
        "df_summary = pd.DataFrame(results_summary)\n"
        "pd.set_option('display.width', 220)\n"
        "print('\\n================= FINAL MODEL INTERCOMPARISON TABLE =================')\n"
        "print(df_summary.to_string(index=False))\n"
        "print('=====================================================================\\n')\n"
        "summary_csv = plots_dir / 'intercomparison_summary_table.csv'\n"
        "df_summary.to_csv(summary_csv, index=False)\n"
        "print(f'Table saved to: {summary_csv}')"
    )

    c9_plot = (
        "# 9. One-Page Summary Map (Real Output from Primary Run)\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import rasterio\n"
        "from matplotlib.colors import ListedColormap\n\n"
        "prim_outputs = case_outputs.get('Base_uniform_50m')\n"
        "prim_dir = base_out_dir / 'Base_uniform_50m' / 'outputs'\n\n"
        "if prim_outputs and (prim_dir / 'intercomparison_agreement_map.tif').exists():\n"
        "    fig, axs = plt.subplots(2, 2, figsize=(14, 12))\n\n"
        "    # Panel 1: Primary Tier-1 Max Depth\n"
        "    with rasterio.open(prim_outputs['max_depth_tif']) as src:\n"
        "        d1 = np.ma.masked_less(src.read(1), 0.05)\n"
        "    im0 = axs[0, 0].imshow(d1, cmap='Blues', vmin=0, vmax=10)\n"
        "    axs[0, 0].set_title('(a) Primary Tier-1 Max Depth (m)', fontsize=11, weight='bold')\n"
        "    fig.colorbar(im0, ax=axs[0, 0], shrink=0.7, label='Depth (m)')\n\n"
        "    # Panel 2: Model Intercomparison Agreement Map\n"
        "    with rasterio.open(prim_dir / 'intercomparison_agreement_map.tif') as src:\n"
        "        agr = src.read(1)\n"
        "    cmap_agr = ListedColormap(['#f0f0f0', '#2b83ba', '#fdae61', '#d7191c'])\n"
        "    im1 = axs[0, 1].imshow(agr, cmap=cmap_agr, vmin=0, vmax=3)\n"
        "    axs[0, 1].set_title('(b) Intercomparison Agreement', fontsize=11, weight='bold')\n"
        "    cbar1 = fig.colorbar(im1, ax=axs[0, 1], ticks=[0, 1, 2, 3], shrink=0.7)\n"
        "    cbar1.ax.set_yticklabels(['Dry', 'Both Wet', 'Tier-0 Only', 'Tier-1 Only'])\n\n"
        "    # Panel 3: Primary Tier-1 Max Flow Velocity\n"
        "    with rasterio.open(prim_outputs['max_velocity_tif']) as src:\n"
        "        v1 = np.ma.masked_less(src.read(1), 0.05)\n"
        "    im2 = axs[1, 0].imshow(v1, cmap='magma', vmin=0, vmax=8)\n"
        "    axs[1, 0].set_title('(c) Max Velocity (m/s)', fontsize=11, weight='bold')\n"
        "    fig.colorbar(im2, ax=axs[1, 0], shrink=0.7, label='Velocity (m/s)')\n\n"
        "    # Panel 4: Primary Arrival Time (threshold 0.05 m)\n"
        "    with rasterio.open(prim_outputs['arrival_time_0_05_tif']) as src:\n"
        "        arr = src.read(1)\n"
        "        arr_min = np.ma.masked_invalid(arr) / 60.0\n"
        "    im3 = axs[1, 1].imshow(arr_min, cmap='viridis_r', vmin=0, vmax=90)\n"
        "    axs[1, 1].set_title('(d) Arrival Time at 0.05 m (min)', fontsize=11, weight='bold')\n"
        "    fig.colorbar(im3, ax=axs[1, 1], shrink=0.7, label='Arrival Time (minutes)')\n\n"
        "    for ax in axs.flat:\n"
        "        ax.set_xticks([])\n"
        "        ax.set_yticks([])\n\n"
        "    title_txt = (\n"
        "        'PravahX Model Intercomparison: Tier-0 HAND vs Tier-1 Delft3D FM\\n'\n"
        "        'Ganga Reach near Rishikesh | Hypothetical Scenario (Q_peak = 5,000 m3/s)'\n"
        "    )\n"
        "    plt.suptitle(title_txt, fontsize=13, weight='bold')\n"
        "    plt.tight_layout()\n"
        "    summary_png = plots_dir / 'ganga_tier1_summary.png'\n"
        "    plt.savefig(summary_png, dpi=180, bbox_inches='tight')\n"
        "    plt.show()\n"
        "    print(f'Summary map saved: {summary_png}')\n"
        "else:\n"
        "    print('Summary map skipped because validity gates failed or output missing.')"
    )

    c10_archive = (
        "# 10. Save all results and timestamped archive to Drive\n"
        "import shutil\n"
        "import time\n"
        "from pathlib import Path\n\n"
        "ts_str = time.strftime('%Y%m%d_%H%M%S')\n"
        "drive_res_dir = Path(f'/content/drive/MyDrive/PravahX/ganga_tier1_results_{ts_str}')\n"
        "drive_res_dir.mkdir(parents=True, exist_ok=True)\n\n"
        "for f in plots_dir.iterdir():\n"
        "    shutil.copy(f, drive_res_dir / f.name)\n\n"
        "prim_dir = base_out_dir / 'Base_uniform_50m' / 'outputs'\n"
        "if prim_dir.exists():\n"
        "    for f in prim_dir.iterdir():\n"
        "        shutil.copy(f, drive_res_dir / f.name)\n\n"
        "report_file = drive_res_dir / 'INTERCOMPARISON_REPORT.txt'\n"
        "with open(report_file, 'w', encoding='utf-8') as rf:\n"
        "    rf.write('PravahX Ganga Tier-1 vs Tier-0 Model Intercomparison\\n')\n"
        "    rf.write(f'Timestamp: {ts_str}\\n')\n"
        "    rf.write(f'Engine Bundle SHA-256: {EXPECTED_SHA}\\n')\n"
        "    rf.write(f'PravahX Commit: {commit_info}\\n\\n')\n"
        "    rf.write('Summary Table:\\n')\n"
        "    rf.write(df_summary.to_string(index=False) + '\\n')\n\n"
        "print(f'All results successfully archived to Google Drive: {drive_res_dir}')"
    )

    cells = [
        md_cell(header_md),
        code_cell(c1_drive),
        code_cell(c2_engine),
        code_cell(c3_clone),
        code_cell(c4_inputs),
        code_cell(c5_domain_plot),
        code_cell(c6_hydrograph),
        code_cell(c7_runs),
        code_cell(c8_table),
        code_cell(c9_plot),
        code_cell(c10_archive),
    ]

    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
            "colab": {"provenance": []},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }

    nb_path = Path("notebooks/PravahX_Ganga_Tier1.ipynb")
    nb_path.parent.mkdir(parents=True, exist_ok=True)
    nb_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"Created {nb_path}, size: {nb_path.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
